backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "veritabani"
    label: "Haber Veritabani"
    files:
      - label: "Tum Haberleri Yonet"
        name: "haberler"
        file: "haberler.json"
        fields:
          - label: "Haber Listesi"
            name: "haber_listesi"
            widget: "list"
            collapsed: false
            summary: '{{fields.title}}'
            fields:
              - {label: "Baslik", name: "title", widget: "string"}
              - {label: "Kategori", name: "category", widget: "select", options: ["Son Dakika", "Siyaset", "Ekonomi", "Spor", "Teknoloji", "Kültür-Sanat", "Genel"]}
              - {label: "Yayin Tarihi", name: "date", widget: "datetime"}
              - {label: "Kapak Resmi", name: "thumbnail", widget: "image", required: false}
              - {label: "Yazar", name: "author", widget: "string", default: "Ahmet Nar"}
              - {label: "Ozet", name: "description", widget: "text"}
              - {label: "Haber Icerigi", name: "body", widget: "markdown"}
              
  - name: "yazarlar_veritabani"
    label: "Yazarlar ve Profiller"
    files:
      - label: "Yazar Listesi Yonet"
        name: "yazarlar"
        file: "yazarlar.json"
        fields:
          - label: "Yazar Listesi"
            name: "yazar_listesi"
            widget: "list"
            collapsed: false
            summary: '{{fields.name}}'
            fields:
              - {label: "Yazar Adi Soyadi", name: "name", widget: "string"}
              - {label: "Profil Fotografi", name: "avatar", widget: "image", required: false}
              - {label: "Biyografi", name: "bio", widget: "text"}